name: Run Tests

on:
  push:
    branches: [ main, os-checker ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install precompiled binaries
        run: |
          wget https://github.com/rust-embedded/cargo-binutils/releases/download/v0.3.6/x86_64-unknown-linux-gnu.tar.gz
          tar xzvf x86_64-unknown-linux-gnu.tar.gz
          mv x86_64-unknown-linux-gnu/* ~/.cargo/bin/
          sudo apt install -y qemu-system gcc-riscv64-linux-gnu

      - name: Test
        run: |
          ./test_all.sh | tee stdout.txt

          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat stdout.txt | awk "/Summary for tests/,/END/" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
